// Generated by npm run build:timeline-links. Source metadata remains in the chronology data.
export const TIMELINE_ENCYCLOPEDIA_CREDITS = [
  {
    "id": "ot",
    "title": "Encyclopedia of the Bible: Old Testament chronology",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Chronology-Old-Testament",
    "use": "Comparison of calendar anchors and chronological interpretations. Its alternative textual readings are not substituted for the KJV."
  },
  {
    "id": "nt",
    "title": "Encyclopedia of the Bible: New Testament chronology",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Chronology-New-Testament",
    "use": "Calendar proposals for Jesus, Paul, and the apostolic period. KJV passage details and relative order control the reconstruction."
  },
  {
    "id": "artaxerxes",
    "title": "Encyclopaedia Iranica: Artaxerxes I",
    "url": "https://www.iranicaonline.org/articles/artaxerxes-i/",
    "use": "Reign c. 465/464–424/423 BC. Ezra and Nehemiah placements use the conventional identification with Artaxerxes I and allow calendar boundaries."
  },
  {
    "id": "gallio",
    "title": "Encyclopedia of the Bible: Gallio",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Gallio",
    "use": "Delphi inscription and the proposed AD 51–52 or 52–53 proconsulship, anchoring Paul's Corinth episode."
  },
  {
    "id": "festus",
    "title": "Encyclopedia of the Bible: Porcius Festus",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Porcius-Festus",
    "use": "Discusses disputed accession proposals from AD 57 to 60. The displayed later-Paul sequence uses AD 60 provisionally; this is not a settled date."
  },
  {
    "id": "romans",
    "title": "Encyclopedia of the Bible: Romans",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Epistle-Romans",
    "use": "Corinth and the Jerusalem collection as clues to the letter's setting; proposed dates differ with Paul's travel chronology."
  },
  {
    "id": "corinthians",
    "title": "Encyclopedia of the Bible: First Corinthians",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/First-Epistle-Corinthians",
    "use": "Ephesian setting and approximate mid-50s chronology, compared with the KJV's travel notices."
  },
  {
    "id": "thessalonians",
    "title": "Encyclopedia of the Bible: First Thessalonians",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/First-Epistle-Thessalonians",
    "use": "Timothy's report and a proposed second-journey setting, commonly Corinth; the letter itself does not give an AD year."
  },
  {
    "id": "peter1",
    "title": "Encyclopedia of the Bible: First Peter",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/First-Epistle-Peter",
    "use": "Traditional early-to-mid-60s proposal and discussion of Babylon; the KJV's place name is retained."
  },
  {
    "id": "peter2",
    "title": "Encyclopedia of the Bible: Second Peter",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Second-Epistle-Peter",
    "use": "Date before Peter's death in the traditional AD 64–68 setting; an external proposal, not a KJV death date."
  },
  {
    "id": "james",
    "title": "Encyclopedia of the Bible: James",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Epistle-James",
    "use": "Dating depends partly on which James is identified as the author. This dataset leaves the calendar placement unassigned."
  },
  {
    "id": "johnLetters",
    "title": "Encyclopedia of the Bible: The Epistles of John",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Epistles-John",
    "use": "Traditional late-first-century setting. The displayed AD 85–95 window is a broad editorial allowance around late-80s/early-90s proposals, not an exact writing span."
  },
  {
    "id": "revelation",
    "title": "Encyclopedia of the Bible: Revelation",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Book-Revelation",
    "use": "Discusses early and late dating proposals. Patmos is retained from Revelation 1:9, with no selected calendar year or prophetic fulfillment scheme."
  },
  {
    "id": "omri",
    "title": "Encyclopedia of the Bible: Omri",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Omri",
    "use": "Calendar comparison for Omri's divided and sole rule and Ahab's c. 874/873 BC accession. KJV reign totals are retained."
  },
  {
    "id": "jehu",
    "title": "Encyclopedia of the Bible: Jehu",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Jehu",
    "use": "Assyrian synchronisms and the proposed c. 853 BC Ahab / c. 841 BC Jehu transition dates. These are calendar reconstructions, not dates printed in Kings."
  },
  {
    "id": "isaiahContext",
    "title": "Encyclopedia of the Bible: Isaiah",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Isaiah",
    "use": "Calendar comparison for Uzziah's death around 740/739 BC and Isaiah's named royal setting. The shared Hezekiah chronology is retained; the source's other chronological or textual proposals are not substituted for the KJV."
  },
  {
    "id": "estherContext",
    "title": "Encyclopedia of the Bible: Book of Esther",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Book-Esther",
    "use": "The proposed identification of Ahasuerus as Xerxes I, 486–465 BC, and the third-, seventh-, and twelfth-year sequence. Alternative king identifications would change the BC dates."
  },
  {
    "id": "socrates",
    "title": "Stanford Encyclopedia of Philosophy: Socrates",
    "url": "https://plato.stanford.edu/entries/socrates/",
    "use": "Life and historical evidence, c. 469–399 BC."
  },
  {
    "id": "plato",
    "title": "Stanford Encyclopedia of Philosophy: Plato",
    "url": "https://plato.stanford.edu/entries/plato/",
    "use": "Life, c. 429–347 BC; the birth year is uncertain."
  },
  {
    "id": "aristotle",
    "title": "Stanford Encyclopedia of Philosophy: Aristotle",
    "url": "https://plato.stanford.edu/entries/aristotle/",
    "use": "Life, 384–322 BC, and association with Plato's Academy."
  }
];
