// Generated by npm run build:timeline-links. Source metadata remains in the chronology data.
export const TIMELINE_SOURCE_CREDITS = [
  {
    "id": "crucifixionStudy",
    "title": "Humphreys & Waddington: Dating the Crucifixion (1983)",
    "url": "https://www.nature.com/articles/306743a0",
    "use": "Published AD 33 proposal using reconstructed calendars and a proposed lunar-eclipse association. Its interpretation is not a KJV statement or an adopted exact date; the chart retains the provisional AD 30 framework."
  },
  {
    "id": "ot",
    "title": "Encyclopedia of the Bible: Old Testament chronology",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Chronology-Old-Testament",
    "use": "Comparison of calendar anchors and chronological interpretations. Its alternative textual readings are not substituted for the KJV."
  },
  {
    "id": "nt",
    "title": "Encyclopedia of the Bible: New Testament chronology",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Chronology-New-Testament",
    "use": "Calendar proposals for Jesus, Paul, and the apostolic period. KJV passage details and relative order control the reconstruction."
  },
  {
    "id": "jerusalem",
    "title": "British Museum: Babylonian Chronicle, BM 21946",
    "url": "https://www.britishmuseum.org/collection/object/W_1896-0409-51",
    "use": "Independent evidence for Nebuchadnezzar's capture of Jerusalem in 597 BC."
  },
  {
    "id": "cyrus",
    "title": "Livius: Cyrus the Great",
    "url": "https://www.livius.org/articles/person/cyrus-the-great/",
    "use": "Reign from accession in Anshan, c. 559–530 BC; conquest of Babylon in 539 BC. Ezra supplies the return decree; the external chronology does not override that account."
  },
  {
    "id": "alexander",
    "title": "Livius: Alexander the Great",
    "url": "https://www.livius.org/articles/person/alexander-the-great/",
    "use": "Historical context between the Testaments: Alexander's reign and conquest of Persia."
  },
  {
    "id": "antiochus",
    "title": "Livius: Antiochus IV Epiphanes",
    "url": "https://www.livius.org/articles/person/antiochus-iv-epiphanes/",
    "use": "Historical context for persecution and the Maccabean revolt, not a date assigned to a prophecy."
  },
  {
    "id": "herod",
    "title": "Livius: Herod the Great",
    "url": "https://www.livius.org/articles/person/herod-the-great/",
    "use": "Historical proposals for Herod's reign and death; the birth of Jesus remains approximate."
  },
  {
    "id": "assyria",
    "title": "Livius: Sennacherib's prism (translated inscription)",
    "url": "https://www.livius.org/sources/content/anet/287-the-sennacherib-prism/",
    "use": "Assyrian royal chronology and the 701 BC campaign. The king's account is partial; it does not override the KJV account of Jerusalem's deliverance."
  },
  {
    "id": "artaxerxes",
    "title": "Encyclopaedia Iranica: Artaxerxes I",
    "url": "https://www.iranicaonline.org/articles/artaxerxes-i/",
    "use": "Reign c. 465/464–424/423 BC. Ezra and Nehemiah placements use the conventional identification with Artaxerxes I and allow calendar boundaries."
  },
  {
    "id": "claudius",
    "title": "Livius: Claudius",
    "url": "https://www.livius.org/articles/person/claudius/",
    "use": "Roman imperial reign, AD 41–54; background to Acts 11 and 18."
  },
  {
    "id": "agrippa",
    "title": "Livius: Herod Agrippa I",
    "url": "https://www.livius.org/articles/person/herod-agrippa-i/",
    "use": "Reign AD 37–44 and death in AD 44, with Josephus, Antiquities 19.343–350. Distinct from Agrippa II in Acts 25–26."
  },
  {
    "id": "gallio",
    "title": "Encyclopedia of the Bible: Gallio",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Gallio",
    "use": "Delphi inscription and the proposed AD 51–52 or 52–53 proconsulship, anchoring Paul's Corinth episode."
  },
  {
    "id": "festus",
    "title": "Encyclopedia of the Bible: Porcius Festus",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Porcius-Festus",
    "use": "Discusses disputed accession proposals from AD 57 to 60. The displayed later-Paul sequence uses AD 60 provisionally; this is not a settled date."
  },
  {
    "id": "nero",
    "title": "Livius: Nero",
    "url": "https://www.livius.org/articles/person/nero/",
    "use": "Imperial reign AD 54–68; political context for Paul's appeal and Roman custody, not evidence that he met Nero."
  },
  {
    "id": "romans",
    "title": "Encyclopedia of the Bible: Romans",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Epistle-Romans",
    "use": "Corinth and the Jerusalem collection as clues to the letter's setting; proposed dates differ with Paul's travel chronology."
  },
  {
    "id": "corinthians",
    "title": "Encyclopedia of the Bible: First Corinthians",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/First-Epistle-Corinthians",
    "use": "Ephesian setting and approximate mid-50s chronology, compared with the KJV's travel notices."
  },
  {
    "id": "thessalonians",
    "title": "Encyclopedia of the Bible: First Thessalonians",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/First-Epistle-Thessalonians",
    "use": "Timothy's report and a proposed second-journey setting, commonly Corinth; the letter itself does not give an AD year."
  },
  {
    "id": "peter1",
    "title": "Encyclopedia of the Bible: First Peter",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/First-Epistle-Peter",
    "use": "Traditional early-to-mid-60s proposal and discussion of Babylon; the KJV's place name is retained."
  },
  {
    "id": "peter2",
    "title": "Encyclopedia of the Bible: Second Peter",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Second-Epistle-Peter",
    "use": "Date before Peter's death in the traditional AD 64–68 setting; an external proposal, not a KJV death date."
  },
  {
    "id": "james",
    "title": "Encyclopedia of the Bible: James",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Epistle-James",
    "use": "Dating depends partly on which James is identified as the author. This dataset leaves the calendar placement unassigned."
  },
  {
    "id": "johnLetters",
    "title": "Encyclopedia of the Bible: The Epistles of John",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Epistles-John",
    "use": "Traditional late-first-century setting. The displayed AD 85–95 window is a broad editorial allowance around late-80s/early-90s proposals, not an exact writing span."
  },
  {
    "id": "revelation",
    "title": "Encyclopedia of the Bible: Revelation",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Book-Revelation",
    "use": "Discusses early and late dating proposals. Patmos is retained from Revelation 1:9, with no selected calendar year or prophetic fulfillment scheme."
  },
  {
    "id": "domitian",
    "title": "Livius: Domitian",
    "url": "https://www.livius.org/articles/person/domitian/",
    "use": "Imperial reign, AD 81–96; background to the proposed late-first-century letter setting, not proof of a specific persecution or meeting."
  },
  {
    "id": "omri",
    "title": "Encyclopedia of the Bible: Omri",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Omri",
    "use": "Calendar comparison for Omri's divided and sole rule and Ahab's c. 874/873 BC accession. KJV reign totals are retained."
  },
  {
    "id": "jehu",
    "title": "Encyclopedia of the Bible: Jehu",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Jehu",
    "use": "Assyrian synchronisms and the proposed c. 853 BC Ahab / c. 841 BC Jehu transition dates. These are calendar reconstructions, not dates printed in Kings."
  },
  {
    "id": "assyrianIsrael",
    "title": "UCL / Oracc: Israel, the House of Omri",
    "url": "https://oracc.museum.upenn.edu/saao/aebp/Essentials/Countries/Israel/index.html",
    "use": "Assyrian evidence for Jehu's tribute and the eighth-century interventions. Imperial claims do not override the biblical narrative or establish biological descent from Omri."
  },
  {
    "id": "tiglath",
    "title": "UCL / Oracc: Tiglath-pileser III",
    "url": "https://oracc.museum.upenn.edu/saao/aebp/Essentials/Kings/Tiglath-pileserIII/index.html",
    "use": "Assyrian reign c. 744–727 BC (745 used for accession elsewhere), and the 732 BC Damascus/Israel campaign. Calendar setting for 2 Kings 15–16."
  },
  {
    "id": "isaiahContext",
    "title": "Encyclopedia of the Bible: Isaiah",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Isaiah",
    "use": "Calendar comparison for Uzziah's death around 740/739 BC and Isaiah's named royal setting. The shared Hezekiah chronology is retained; the source's other chronological or textual proposals are not substituted for the KJV."
  },
  {
    "id": "estherContext",
    "title": "Encyclopedia of the Bible: Book of Esther",
    "url": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/Book-Esther",
    "use": "The proposed identification of Ahasuerus as Xerxes I, 486–465 BC, and the third-, seventh-, and twelfth-year sequence. Alternative king identifications would change the BC dates."
  },
  {
    "id": "ashdod",
    "title": "ORACC · Sargon II and the annexation of Ashdod",
    "url": "https://oracc.museum.upenn.edu/saao/aebp/essentials/kings/sargonii/",
    "use": "Assyrian evidence places Ashdod's annexation in 711 BC. Isaiah 20 names Sargon and the campaign; the three-year sign is retained without invented endpoints."
  },
  {
    "id": "zechariahCalendar",
    "title": "Zechariah 1:7 · calendar comparison",
    "url": "https://www.biblegateway.com/verse/en/Zechariah%201%3A7",
    "use": "Calendar annotations place Darius's second-year, eleventh-month vision in 519 BC. The KJV's year, month, and day remain primary; only an approximate year is plotted."
  },
  {
    "id": "psalmHeading3",
    "title": "KJV Psalm 3 heading",
    "url": "https://biblehub.com/kjv/psalms/3-1.htm",
    "use": "KJV superscription, omitted from the bundled numbered verses. A named occasion supplies context without inventing an absolute composition year."
  },
  {
    "id": "psalmHeading34",
    "title": "KJV Psalm 34 heading",
    "url": "https://biblehub.com/kjv/psalms/34-1.htm",
    "use": "KJV superscription, omitted from the bundled numbered verses. A named occasion supplies context without inventing an absolute composition year."
  },
  {
    "id": "psalmHeading51",
    "title": "KJV Psalm 51 heading",
    "url": "https://biblehub.com/kjv/psalms/51-1.htm",
    "use": "KJV superscription, omitted from the bundled numbered verses. A named occasion supplies context without inventing an absolute composition year."
  },
  {
    "id": "psalmHeading52",
    "title": "KJV Psalm 52 heading",
    "url": "https://biblehub.com/kjv/psalms/52-1.htm",
    "use": "KJV superscription, omitted from the bundled numbered verses. A named occasion supplies context without inventing an absolute composition year."
  },
  {
    "id": "psalmHeading54",
    "title": "KJV Psalm 54 heading",
    "url": "https://biblehub.com/kjv/psalms/54-1.htm",
    "use": "KJV superscription, omitted from the bundled numbered verses. A named occasion supplies context without inventing an absolute composition year."
  },
  {
    "id": "psalmHeading56",
    "title": "KJV Psalm 56 heading",
    "url": "https://biblehub.com/kjv/psalms/56-1.htm",
    "use": "KJV superscription, omitted from the bundled numbered verses. A named occasion supplies context without inventing an absolute composition year."
  },
  {
    "id": "psalmHeading57",
    "title": "KJV Psalm 57 heading",
    "url": "https://biblehub.com/kjv/psalms/57-1.htm",
    "use": "KJV superscription, omitted from the bundled numbered verses. A named occasion supplies context without inventing an absolute composition year."
  },
  {
    "id": "psalmHeading59",
    "title": "KJV Psalm 59 heading",
    "url": "https://biblehub.com/kjv/psalms/59-1.htm",
    "use": "KJV superscription, omitted from the bundled numbered verses. A named occasion supplies context without inventing an absolute composition year."
  },
  {
    "id": "psalmHeading60",
    "title": "KJV Psalm 60 heading",
    "url": "https://biblehub.com/kjv/psalms/60-1.htm",
    "use": "KJV superscription, omitted from the bundled numbered verses. A named occasion supplies context without inventing an absolute composition year."
  },
  {
    "id": "psalmHeading63",
    "title": "KJV Psalm 63 heading",
    "url": "https://biblehub.com/kjv/psalms/63-1.htm",
    "use": "KJV superscription, omitted from the bundled numbered verses. A named occasion supplies context without inventing an absolute composition year."
  },
  {
    "id": "psalmHeading90",
    "title": "KJV Psalm 90 heading",
    "url": "https://biblehub.com/kjv/psalms/90-1.htm",
    "use": "KJV superscription, omitted from the bundled numbered verses. A named occasion supplies context without inventing an absolute composition year."
  },
  {
    "id": "psalmHeading142",
    "title": "KJV Psalm 142 heading",
    "url": "https://biblehub.com/kjv/psalms/142-1.htm",
    "use": "KJV superscription, omitted from the bundled numbered verses. A named occasion supplies context without inventing an absolute composition year."
  },
  {
    "id": "josephusAntiquities",
    "title": "Josephus, Antiquities 20.11.3: completion notice",
    "url": "https://penelope.uchicago.edu/josephus/ant-20.html",
    "use": "Josephus dates completion to Domitian's thirteenth year, conventionally AD 93–94. This dates his writing, not the earlier biblical events retold in it."
  },
  {
    "id": "plinyElder",
    "title": "Livius: Pliny the Elder",
    "url": "https://www.livius.org/articles/person/pliny-the-elder/",
    "use": "Roman author and officer, born AD 23 or 24, died AD 79. The chart uses 23 as the approximate birth anchor. His Roman education supplies geographic context."
  },
  {
    "id": "pilate",
    "title": "Livius: Pontius Pilate",
    "url": "https://www.livius.org/articles/person/pontius-pilate/",
    "use": "Prefecture AD 26–36 only. The article's judgments about the Gospel accounts are not adopted; the KJV controls the trial narrative."
  },
  {
    "id": "seneca",
    "title": "Stanford Encyclopedia of Philosophy: Seneca",
    "url": "https://plato.stanford.edu/entries/seneca/",
    "use": "Life c. 1 BC–AD 65 in this source, Roman education, Stoic philosophy and service under Nero. Other birth estimates differ; no contact with Paul is inferred."
  },
  {
    "id": "vespasian",
    "title": "Livius: Vespasian",
    "url": "https://www.livius.org/articles/person/vespasian/",
    "use": "Imperial reign AD 69–79 and political setting of Titus's AD 70 Jerusalem campaign."
  },
  {
    "id": "romeFire",
    "title": "Tacitus, Annals 15.38–44: Rome's fire and persecution",
    "url": "https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Tacitus/Annals/15B*.html#38",
    "use": "Ancient account of the AD 64 fire and Nero's punishment of Christians. This hostile source is not adopted as theology or proof of the fire's cause."
  },
  {
    "id": "jerusalem70",
    "title": "Livius: Titus' siege of Jerusalem",
    "url": "https://www.livius.org/articles/concept/roman-jewish-wars/roman-jewish-wars-4/",
    "use": "Historical AD 70 siege and destruction of the temple. No inferred date of Gospel composition or automatic identification of every prophecy with this event."
  },
  {
    "id": "nabonidusChronicle",
    "title": "Nabonidus Chronicle (ABC 7), translated by A. K. Grayson",
    "url": "https://www.livius.org/sources/content/mesopotamian-chronicles-content/abc-7-nabonidus-chronicle/",
    "use": "External regnal framework, c. 556–539 BC, and the conquest of Babylon. The damaged chronicle does not identify Darius the Mede or replace Daniel's account."
  },
  {
    "id": "cambyses",
    "title": "Livius: Cambyses II",
    "url": "https://www.livius.org/articles/person/cambyses-ii/",
    "use": "Reign 530–522 BC and conquest of Egypt in 525 BC. Supplies Persian political context without identifying the kings in Ezra's later correspondence."
  },
  {
    "id": "nebuchadnezzar",
    "title": "Livius: Nebuchadnezzar II",
    "url": "https://www.livius.org/articles/person/nebuchadnezzar-ii/",
    "use": "Conventional reign, 605–562 BC; not birth and death dates."
  },
  {
    "id": "darius",
    "title": "Livius: Darius the Great",
    "url": "https://www.livius.org/articles/person/darius-the-great/",
    "use": "Reign of Darius I, 522–486 BC; distinct from Darius the Mede."
  },
  {
    "id": "augustus",
    "title": "Livius: Augustus",
    "url": "https://www.livius.org/articles/person/augustus/",
    "use": "Imperial reign, 27 BC–AD 14."
  },
  {
    "id": "tiberius",
    "title": "Livius: Tiberius",
    "url": "https://www.livius.org/articles/person/tiberius/",
    "use": "Reign, AD 14–37. Luke's fifteenth-year reckoning is discussed separately."
  },
  {
    "id": "socrates",
    "title": "Stanford Encyclopedia of Philosophy: Socrates",
    "url": "https://plato.stanford.edu/entries/socrates/",
    "use": "Life and historical evidence, c. 469–399 BC."
  },
  {
    "id": "plato",
    "title": "Stanford Encyclopedia of Philosophy: Plato",
    "url": "https://plato.stanford.edu/entries/plato/",
    "use": "Life, c. 429–347 BC; the birth year is uncertain."
  },
  {
    "id": "aristotle",
    "title": "Stanford Encyclopedia of Philosophy: Aristotle",
    "url": "https://plato.stanford.edu/entries/aristotle/",
    "use": "Life, 384–322 BC, and association with Plato's Academy."
  }
];
export const TIMELINE_WEBSITE_CREDITS = [
  {
    "label": "Bible Hub",
    "href": "https://biblehub.com/",
    "description": "Comparison references for KJV Psalm headings."
  },
  {
    "label": "British Museum",
    "href": "https://www.britishmuseum.org/",
    "description": "Artifacts and records supporting historical date comparisons."
  },
  {
    "label": "Encyclopaedia Iranica",
    "href": "https://www.iranicaonline.org/",
    "description": "Persian rulers and historical background."
  },
  {
    "label": "Encyclopedia of the Bible",
    "href": "https://www.biblegateway.com/resources/encyclopedia-of-the-bible/toc",
    "description": "Biblical chronology, people, and book backgrounds."
  },
  {
    "label": "LacusCurtius — University of Chicago",
    "href": "https://penelope.uchicago.edu/",
    "description": "Ancient historical texts, including Josephus and Tacitus."
  },
  {
    "label": "Livius",
    "href": "https://www.livius.org/",
    "description": "Ancient history, rulers, and translated historical texts."
  },
  {
    "label": "Nature",
    "href": "https://www.nature.com/",
    "description": "Research comparing proposed crucifixion dates."
  },
  {
    "label": "ORACC",
    "href": "https://oracc.museum.upenn.edu/",
    "description": "Assyrian inscriptions and historical records."
  },
  {
    "label": "Stanford Encyclopedia of Philosophy",
    "href": "https://plato.stanford.edu/",
    "description": "Philosophers and their historical context."
  }
];
